config/routes.rb
Rails.application.routes.draw do
  resources :basket_items

  resources :baskets

  get 'store/index'

  resources :items

  root to: 'store#index', as: 'store'

end

app/models/basket.rb
class Basket < ActiveRecord::Base
  has_many :basket_items, dependent: :destroy

  def add_item(item)
    basket_items.build(item: item)
  end

  def sum
		total = 0
		basket_items.each {|li| total += li.item.price }
		total
  end

  def add_free_delivery
  	if sum > 500
  		delivery = 0
  	else
  		delivery = 50
  	end
  end

end

app/models/basket_item.rb
class BasketItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :basket
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :basket_items
	validates :title, :price, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  include CurrentBasket
  before_action :set_basket, only: [:create]
  before_action :set_basket_item, only: [:show, :edit, :update, :destroy]

  # GET /basket_items
  # GET /basket_items.json
  def index
    @basket_items = BasketItem.all
  end

  # GET /basket_items/1
  # GET /basket_items/1.json
  def show
  end

  # GET /basket_items/new
  def new
    @basket_item = BasketItem.new
  end

  # GET /basket_items/1/edit
  def edit
  end

  # POST /basket_items
  # POST /basket_items.json
  def create
    item = Item.find(params[:item_id])
    @basket_item = @basket.add_item(item)
    @basket_item.save
      if @basket.basket_items.count <= 10
        redirect_to @basket_item.basket
        flash[:success] = "Добавлен товар в корзину: #{item.title}"
      else
        redirect_to @basket_item.basket
        flash[:error] = "Слишком много товаров в корзине. Должно быть не больше 10. Удалите лишние."
      end
  end

  # PATCH/PUT /basket_items/1
  # PATCH/PUT /basket_items/1.json
  def update
    respond_to do |format|
      if @basket_item.update(basket_item_params)
        format.html { redirect_to @basket_item, notice: 'Basket item was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket_item }
      else
        format.html { render :edit }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/1
  # DELETE /basket_items/1.json
  def destroy
    @basket_item.destroy
    current_basket = session[:basket_id]
    redirect_to basket_url(current_basket)
    flash[:success] = 'Товар успешно удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket_item
      @basket_item = BasketItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_item_params
      params.require(:basket_item).permit(:item_id, :basket_id)
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    session[:basket_total] = @basket.sum
    @delivery = @basket.add_free_delivery
  end

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # GET /baskets/1/edit
  def edit
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy if @basket.id == session[:basket_id]
    session[:basket_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      @basket = Basket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_params
      params.fetch(:basket, {})
    end
end

app/controllers/concerns/current_basket.rb
module CurrentBasket
  extend ActiveSupport::Concern

  private

    def set_basket
      @basket = Basket.find(session[:basket_id])
    rescue ActiveRecord::RecordNotFound
      @basket = Basket.create
      session[:basket_id] = @basket.id
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@items = Item.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/basket_items/_form.html.erb
<%= form_for(@basket_item) do |f| %>
  <% if @basket_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket_item.errors.count, "error") %> prohibited this basket_item from being saved:</h2>

      <ul>
      <% @basket_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :basket_id %><br>
    <%= f.text_field :basket_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basket_items/edit.html.erb
<h1>Editing basket_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket_item %> |
<%= link_to 'Back', basket_items_path %>

app/views/basket_items/index.html.erb
<h1>Listing basket_items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Basket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basket_items.each do |basket_item| %>
      <tr>
        <td><%= basket_item.item %></td>
        <td><%= basket_item.basket %></td>
        <td><%= link_to 'Show', basket_item %></td>
        <td><%= link_to 'Edit', edit_basket_item_path(basket_item) %></td>
        <td><%= link_to 'Destroy', basket_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket item', new_basket_item_path %>

app/views/basket_items/new.html.erb
<h1>New basket_item</h1>

<%= render 'form' %>

<%= link_to 'Back', basket_items_path %>

app/views/basket_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @basket_item.item %>
</p>

<p>
  <strong>Basket:</strong>
  <%= @basket_item.basket %>
</p>

<%= link_to 'Edit', edit_basket_item_path(@basket_item) %> |
<%= link_to 'Back', basket_items_path %>

app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<h1>Listing baskets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<% flash.each do |key, value| %>
	<%= content_tag(:div, value, class: "#{key}") %>
<% end %>

<h2>Your Basket</h2>

<ul>
  <% @basket.basket_items.each do |i| %>
    <li><%= i.item.title %> | <%= link_to 'Remove', i, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>
Total - <%= number_to_currency(session[:basket_total]) %> </br>
Delivery - <%= number_to_currency(@delivery) %> (free if total > $500.00)</br>

<%= link_to 'Destroy basket', @basket, method: :delete, data: { confirm: 'Are you sure?' } %> </br>
<%= link_to 'Back', store_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magaz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/store/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Catalog</h1>

<% @items.each do |item| %>
  <div>
    <h2><%= item.title %> - <%= number_to_currency(item.price) %>
    <%= button_to 'Add to Basket', basket_items_path(item_id: item) %></h2>
  </div>
<% end %>